server:
  port: ${PORT:8080}
spring:
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/registros}
  redis:
    host: ${REDIS_URL:localhost}
    port: 6379
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    topic: ${TOPIC:parquimetrotopic}
    consumer:
      group-id: ${GROUP_CONSUMER:grupo-parquimetro}
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
topics:
  parquimetrotopic: ${PARQUIMETROTOPIC:parquimetrotopic}
